version: "3.7"
services:
  db:
      image: postgres:13
      env_file:
         - ./.env
      volumes:
        - postgres-db-volume:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "mobilizon_reshare"]
        interval: 5s
        retries: 5
      expose:
        - 5432
  web:
    build: .
    command: poetry run mobilizon-reshare web
    #command: sh
    environment:
      SECRETS_FOR_DYNACONF: /app/.secrets.toml
      SETTINGS_FILE_FOR_DYNACONF: /app/settings.toml
      ENV_FOR_DYNACONF: development
      MOBILIZON_RESHARE_INTERVAL: "*/15 10-18 * * 0-4"
    volumes:
      - ./.secrets.toml:/app/.secrets.toml
      - ./mobilizon_reshare/settings.toml:/app/settings.toml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - postgres-db-volume:/var/lib/postgresql
      - ./:/app

volumes:
  postgres-db-volume:
