[default]
debug = true
default = true
local_state_dir = "/var/mobots"
log_dir = "/var/log/mobots"
db_name = "events.db"
db_path = "@format {this.local_state_dir}/{this.db_name}"

[default.selection]
strategy = "next_event"

[default.selection.strategy_options]
break_between_events_in_minutes =5

[default.publisher.telegram]
active=true
chat_id="xxx"
msg_template_path="xxx"
token="xxx"
username="xxx"
[default.publisher.facebook]
active=false
[default.publisher.zulip]
active=false
[default.publisher.twitter]
active=false
[default.publisher.mastodon]
active=false

[default.notifier.telegram]
active=true
chat_id="xxx"
token="xxx"
username="xxx"
[default.notifier.zulip]
active=false
[default.notifier.twitter]
active=false
[default.notifier.mastodon]
active=false


[default.logging]
version = 1
disable_existing_loggers = false

[default.logging.formatters.standard]
format = '[%(asctime)s] [%(levelno)s] [%(levelname)s] %(message)s'

[default.logging.handlers.console]
level = "INFO"
class = "logging.StreamHandler"
formatter = "standard"
stream = "ext://sys.stderr"

[default.logging.handlers.logfile]
level = "DEBUG"
class = "logging.handlers.RotatingFileHandler"
formatter = "standard"
filename = "@format {this.log_dir}/mobilizon_bots.log"
maxBytes = 52428800
backupCount = 500
encoding = "utf8"

[default.logging.root]
level = "DEBUG"
handlers = ['console', 'logfile']

[testing]
DEBUG = true
LOCAL_STATE_DIR = "/tmp/mobots"
LOG_DIR = "/tmp/mobots"
DB_PATH = ":memory:"